### ISSUE TITLE
Liste des tâches de dev. pour la fonctionnalté "Big Bang"

### ISSUE THREAD

**Issue by Deblak** [Deblak/spot-me#2]
## 🔢 TODO | Fonctionnalité associée #1 

### Gestion de projet : 
 - [x] Choix de la méthode (Kanban, workflow, définition ready/done, labels)
 - [x] Mettre en place un support de communication / documentation (wiki, readme, Jira...)
 - [x] Stratégie de repository, branche, patterns de commentaire Git

### Conception : 
 - [x] Zoning, wireframe, mock up (logo, charte graphique)
 - [x] Mise en place de l'environnement (Git, GitHub, .gitignore)
 - [x] Mise en place de l'environnement de développement de base de données (DBeaver)
 - [x] Mise en place de l'environnement de développement du backend (Eclipse, créaton et init du projet Spring Boot, packages...)
 - [x] Mise en place de l'environnement de développement de frontend (VSCode, création et init du projet Vue, dossier...)
 - [x] Conception de bdd (MCD, MLD, MPD)

 ### Implémentation : 
 - [x] DDL, DML (spots de test)
 - [x] Formulaire de saisie (validation, routeurs, i18n, appel API)
 - [x] Back (API, validation, logique métier, communication bdd)
 - [x] Créer un ou plusieurs endpoints (controller)
 - [x] Créer un ou plusieurs services (service)
 - [x] Créer un ou plusieurs repositories (repository)
 - [x] Créer un ou plusieurs "DTO" (Data transfer Objects)
 - [x]  Créer  une ou plusieurs entités (entity)
 - [x] Tester l'ensemble (UAT)
 
### À venir : 
 - [x] Déploiement
 - [x] Définition des critères d'acceptation
 - [x] Tests unitaires, intégration automatisés
 - [x] Analyse statique du code (Sonar)
